[2023-02-10 17:28:32,848] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2023-02-10 17:28:32,850] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2023-02-10 17:28:32,850] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:28:32,850] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 17:28:32,850] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:28:32,853] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-09-19 00:00:00+00:00
[2023-02-10 17:28:32,855] {standard_task_runner.py:52} INFO - Started process 55184 to run task
[2023-02-10 17:28:32,857] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-09-19T00:00:00+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpl7li241o', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpcrgiwp1w']
[2023-02-10 17:28:32,858] {standard_task_runner.py:80} INFO - Job 76: Subtask extrai_dados
[2023-02-10 17:28:32,873] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-19T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 17:28:32,889] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-09-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-19T00:00:00+00:00
[2023-02-10 17:28:33,007] {local_task_job.py:156} INFO - Task exited with return code Negsignal.SIGSEGV
[2023-02-10 17:28:33,013] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20220919T000000, start_date=20230210T172832, end_date=20230210T172833
[2023-02-10 17:28:33,019] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
