[2023-02-10 17:28:21,143] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2023-02-10 17:28:21,145] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2023-02-10 17:28:21,145] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:28:21,145] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 17:28:21,145] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:28:21,149] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-08-22 00:00:00+00:00
[2023-02-10 17:28:21,151] {standard_task_runner.py:52} INFO - Started process 55139 to run task
[2023-02-10 17:28:21,153] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-08-22T00:00:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmp_dov5r7g', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpjja6_7_a']
[2023-02-10 17:28:21,154] {standard_task_runner.py:80} INFO - Job 68: Subtask extrai_dados
[2023-02-10 17:28:21,169] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-08-22T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 17:28:21,185] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-08-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-22T00:00:00+00:00
[2023-02-10 17:28:21,303] {local_task_job.py:156} INFO - Task exited with return code Negsignal.SIGSEGV
[2023-02-10 17:28:21,308] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20220822T000000, start_date=20230210T172821, end_date=20230210T172821
[2023-02-10 17:28:21,314] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
