[2023-02-10 17:28:44,150] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-17T00:00:00+00:00 [queued]>
[2023-02-10 17:28:44,152] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-17T00:00:00+00:00 [queued]>
[2023-02-10 17:28:44,152] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:28:44,152] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 17:28:44,152] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:28:44,156] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-10-17 00:00:00+00:00
[2023-02-10 17:28:44,158] {standard_task_runner.py:52} INFO - Started process 55221 to run task
[2023-02-10 17:28:44,160] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-10-17T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpg8gf2di8', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpjmc18s5v']
[2023-02-10 17:28:44,161] {standard_task_runner.py:80} INFO - Job 83: Subtask extrai_dados
[2023-02-10 17:28:44,177] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-17T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 17:28:44,195] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-10-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-17T00:00:00+00:00
[2023-02-10 17:28:44,305] {local_task_job.py:156} INFO - Task exited with return code Negsignal.SIGSEGV
[2023-02-10 17:28:44,311] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20221017T000000, start_date=20230210T172844, end_date=20230210T172844
[2023-02-10 17:28:44,316] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
