[2023-02-10 17:28:23,653] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-08-29T00:00:00+00:00 [queued]>
[2023-02-10 17:28:23,656] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-08-29T00:00:00+00:00 [queued]>
[2023-02-10 17:28:23,656] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:28:23,656] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 17:28:23,656] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:28:23,660] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-08-29 00:00:00+00:00
[2023-02-10 17:28:23,662] {standard_task_runner.py:52} INFO - Started process 55149 to run task
[2023-02-10 17:28:23,664] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-08-29T00:00:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpase4_qxt', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmp8y4mnfkg']
[2023-02-10 17:28:23,665] {standard_task_runner.py:80} INFO - Job 70: Subtask extrai_dados
[2023-02-10 17:28:23,680] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-08-29T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 17:28:23,696] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-08-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-29T00:00:00+00:00
[2023-02-10 17:28:23,817] {local_task_job.py:156} INFO - Task exited with return code Negsignal.SIGSEGV
[2023-02-10 17:28:23,822] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20220829T000000, start_date=20230210T172823, end_date=20230210T172823
[2023-02-10 17:28:23,829] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
